Merge FAQ/Contact Page into Main
Darkmono112/Hacksmith2023 pull request #60
Opened 2023-11-03 16:50 UTC by theechosensloth

Closes #50 (create contact page w/ functionality)

2023-11-03 16:58 UTC, paigem33 requested changes
Looks like I can submit a help request that is empty or doesn't have all the data and it still redirects me to the success page. we should probably have some validation on that. It also just shows an empty screen for me since I have no faqs in my database, we should probably seed some in so when people like Erik clone the project they see something there

2023-11-03 16:58 UTC, paigem33 commented on DroneCones/DroneConesApp/views/views.py
> +    pass
Can we remove this?

2023-11-08 17:33 UTC, paigem33 approved these changes
Looks good!

2023-11-09 16:23 UTC, bnsmth235 approved these changes

2023-11-09 16:23 UTC, merged